# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f30a99be1d4291da552d80b08500a954fcf2f150d81f0268ba77f9921fdd3981f9c0fe8b16fe56cdd41b95b4ecedfe5b9a68de1fecd67d101bb8f180c0a55dc

test:
  secret_key_base: ccc0cdfae309c42c22c7f8431047224eaf7fc4ef627a64171d82ac6c25459e6dda460318ea774374dd6da192a8d3ee1eb8ddbd05a12fdbd8c8a6d59a89d27050

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
